name: Push workflow
on:
  push:
    branches: [main]

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install Project Requirements
        run: yarn install
      - name: Set Up ENV
        run: |
          echo "${{ secrets.APP_ID }}" > .env
          echo "${{ secrets.LOG_LEVEL}}" >> .env
          echo "${{ secrets.SSH}}" >> .env
          echo "${{ secrets.WEBHOOK_PROXY_URL}}" >> .env
          echo "${{ secrets.WEBHOOK_SECRET}}" >> .env

  deploy:
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Docker
        run: |
          sudo docker-compose up --build -d
